name: Update workshop template
on:
  push:
    branches:
      - base

jobs:
  update_template:
    name: Update template
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update template
        run: ./scripts/repo/create-github-template.sh
